services:
  server:
    image: pokernode-server:local
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build

  web:
    image: pokernode-web:local
    build:
      context: .
      dockerfile: web/Dockerfile
    pull_policy: build
